# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: ALLFORONETECH.AFOTIDE
PackageVersion: 1.0.0
InstallerType: portable
Commands:
- afot-ide
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ALL-FOR-ONE-TECH/AFOT_IDE/releases/download/v1.0.0/AFOT-IDE.exe
  InstallerSha256: a4a62f541a3e53a32cc71d351617f9da0d3659237076b9f27f91f72229e93983
ManifestType: installer
ManifestVersion: 1.10.0

